# -*- coding: utf-8 -*-
"""flower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AF3fCb97po_uss-TjH582ZQACMFWtGAY
"""

import matplotlib.pyplot as plot
import seaborn as s
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

data = s.load_dataset("iris")
data.head()

x = data.iloc[: , :-1]

y = data.iloc[: , -1]

plot.xlabel('Features')
plot.ylabel('Species')

plotx = data.loc[: , 'sepal_length']
ploty = data.loc[: , 'species']
plot.scatter(plotx , ploty , color="blue" , label = 'sepal_length')

plotx = data.loc[: , 'sepal_width']
ploty = data.loc[: , 'species']
plot.scatter(plotx , ploty , color="green" , label = 'sepal_width')

plotx = data.loc[: , 'petal_length']
ploty = data.loc[: , 'species']
plot.scatter(plotx , ploty , color="red" , label = 'petal_length')

plotx = data.loc[: , 'petal_width']
ploty = data.loc[: , 'species']
plot.scatter(plotx , ploty , color="yellow" , label = 'petal_width')

plot.legend()
plot.show()